version: '2'
services:
  database:
    build: ./db
    environment:
        - MYSQL_ROOT_PASSWORD=rem
  controller:
    build: ./db_controller
    environment:
        - MYSQL_ENV=database
    ports:
     - "5555"
    depends_on:
        - "database"
